local modelsList = {
    "models/foodnhouseholditems/cabbage2.mdl",
    "models/foodnhouseholditems/cabbage1.mdl",
    "models/props_junk/garbage_plasticbottle003a.mdl",
    "models/props_idbs/go/toaster.mdl",
    "models/props_interiors/pot01a.mdl",
    "models/props_c17/chair_stool01a.mdl",
    "models/props_idbs/go/trashcan01.mdl",
    "models/props_junk/propanecanister001a.mdl",
    "models/props_gmod_org/makka12/burgers/burger_box.mdl",
    "models/props/cs_italy/orange.mdl",
    "models/props_gmod_org/makka12/burgers/burger.mdl",
    "models/props/cs_italy/bananna_bunch.mdl",
    "models/props_idbs/go/dish_soap.mdl",
    " models/props_interiors/pot01a.mdl",
    "models/props_c17/chair02a.mdl",
    "models/foodnhouseholditems/toiletpaper2.mdl",
    "models/sims/gm_stove.mdl",
    "models/props/cs_office/water_bottle.mdl",
    "models/props_junk/garbage_glassbottle003a.mdl",
    " models/props_interiors/pot02a.mdl",
    "models/props_idbs/foods/sosis.mdl",
    "models/foodnhouseholditems/fishbass.mdl",
    "models/props_gmod_org/bubba/bubba_spam_comicsize/bubba_spam.mdl",
    "models/foodnhouseholditems/bacon_2.mdl",
    "models/foodnhouseholditems/champagneonplate.mdl",
    "models/foodnhouseholditems/champagne.mdl",
    "models/props_interiors/furniture_chair01a.mdl",
    " models/props_idbs/go/water_cooler.mdl",
    "models/props/cs_office/plant01.mdl",
    "models/props/de_inferno/potted_plant2.mdl",
    "models/props_idbs/go/styrofoam_cups.mdl",
    "models/props/cs_office/computer.mdl",
    "models/props/cs_office/computer_caseb.mdl",
    "models/props_idbs/go/cash_register.mdl",
    "models/props_gmod_org/makka/soda.mdl",
    "models/props_idbs/go_fol/plantairport01.mdl",
    "models/props/de_tides/patio_chair.mdl",
    "models/props_junk/trashbin01a.mdl",
    "models/props/cs_office/offpaintingd.mdl",
    "models/props_downtown/booth_table.mdl",
    "models/foodnhouseholditems/pizzabox.mdl",
    " models/props_gmod_org/neodement/bigsandwich.mdl",
    "models/props/cs_office/cardboard_box01.mdl",
    "models/props_idbs/go/styrofoam_cups_p1.mdl",
    "models/props/cs_office/microwave.mdl",
    "models/props_c17/canister02a.mdl",
    "models/props_c17/canister01a.mdl",
    "models/props_junk/plasticcrate01a.mdl",
    "models/props/cs_office/trash_can.mdl",
    "models/props/cs_militia/caseofbeer01.mdl",
    "models/props_junk/popcan01a.mdl",
    "models/props_junk/gascan001a.mdl",
    "models/props_gmod_org/neodement/cerealbowl.mdl",
    "models/foodnhouseholditems/digestive.mdl",
    "models/foodnhouseholditems/chipstwisties.mdl",
    "models/props_junk/metalbucket01a.mdl",
    "models/props/de_inferno/claypot03.mdl",

}

util.AddNetworkString("RequestModelChange")

net.Receive("RequestModelChange", function(len, ply)
    if ply:Team() == TEAM_PROPS then
        local randomModel = modelsList[math.random(#modelsList)]
        ply:SetModel(randomModel)
    end
end)